### PR TITLE
Misc UI fixes

### LINKED ISSUE #356: Numerous Styling Issues
## Description:
Earlier in the semester, Rebecca identified a bunch of styling issues with Cooper prod. Linked [here](https://www.notion.so/sandboxnu/Rebecca-tears-down-our-website-2ec18273b1f480d6bc2cec9cc5471386)

## TODO:
- Whenever you have the time, anything marked with "quick fix" can be changed. 
  - These issues have very short descriptions, so feel free to ask or have me elaborate on anything
- Yeah go crazy tracy 🫡

### PR DESCRIPTION
**Pull request by gpalmer27**
## Description

As taken from the "rebecca tears down our website" notion page:
- Make it so that unclicking a role type selector selection should make it go back to All
- Get rid of numbers in parentheses (Ex. Co-op (251))
- Make it so that you should be able to click between open filters without having to double click (like having on filter open and then clicking another filter should auto close the current filter and then open the other one in one click)
- Cursor should be the pointer when hovering over a card
- Ensure company info card and the company info page header are the same underlying component/design
- Reset scroll position to top when clicking on new card
- for the company popup, make it close the popup if you click on the role
- Change dropdowns for review form to be the new ones
- Make roles searchable
    - Make all review form inputs searchable
- sidebar open filters — make location + industry alphabetized
- Old cooper logo on the docs page in the docs

## Motivation and Context

Closes #356 

## How has this been tested?

I clicked around a bunch to make sure it worked

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Database migration
  - [ ] Ran `pnpm db:generate` and verified generated SQL migration files in `packages/db/drizzle`

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have moved the ticket to "In Review"
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by songmichael11** [comment]
image
Seems like part of the dropdown is positioned weirdly. It also fails to work for the sidebar too (i assume it's off screen or smth)

File: apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx
Comment (songmichael11) [inline apps/web/src/app/(pages)/(dashboard)/(roles)/page.tsx]: note: i think this data prop can be deleted or super minimized since the only reason we're passing this in afaik is to have the numbers in parentheses (which we're getting rid of)

File: apps/web/src/app/_components/form/sections/basic-info-section.tsx [hunk 1]
```diff
@@ -95,74 +95,78 @@ export function BasicInfoSection({
...
+            { id: "Co-op", label: "Co-op" },
+            { id: "Internship", label: "Internship" },
+          ];
+          return (
+            <FormItem className="flex flex-col w-full pt-4">
+              <FormLabel className="text-sm font-bold text-cooper-gray-400">
+                Job type<span className="text-cooper-red-300">*</span>
+              </FormLabel>
+              <FormControl className="relative w-full">
+                <FilterBody
```
Comment (songmichael11) [inline apps/web/src/app/_components/form/sections/basic-info-section.tsx]: kind of a nit but might be worth renaming from filterbody cause ik there's a Dropdown component and it might be kinda unintuitive if this is the one we're using for our forms
