### PR TITLE
fixed profile width and removed sidebar for reviews page

### LINKED ISSUE #230: (Develop) Fix roles page auto scroll
Currently, clicking on a section on the roles page does not make it clear which section was pressed or which section the page is currently on. The sections sidebar also does not stay in the center of the page. Update the sidebar so there is indication of which section is clicked and the sidebar contents remain centered

### PR DESCRIPTION
**Pull request by gpalmer27**
## Description

Removed the right sidebar on the Reviews page to match the Figma and changed the default width of the profile page.

## Motivation and Context

Matches the Figma

Closes #230 

## How has this been tested?

Clicking around on the website and it all worked!

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Database migration
  - [ ] Ran `pnpm db:generate` and verified generated SQL migration files in `packages/db/drizzle`

## Checklist:

- [ x] My code follows the code style of this project.
- [x ] I have moved the ticket to "In Review"
- [ x] I have added reviewers to this PR
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: apps/web/src/app/_components/reviews/role-info.tsx [hunk 1]
```diff
@@ -314,14 +314,14 @@ export function RoleInfo({ className, roleObj, onBack }: RoleCardProps) {
...
-        <div className="sticky top-10 hidden h-fit w-[15%] flex-col gap-3 text-[#5a5a5a] lg:flex">
+        {/* <div className="sticky top-10 hidden h-fit w-[15%] flex-col gap-3 text-[#5a5a5a] lg:flex">
           <a href="#job-description">Job Description</a>
           <a href="#company">Company</a>
           <a href="#on-the-job">On the job</a>
           <a href="#pay">Pay</a>
           <a href="#interview">Interview</a>
           <a href="#reviews">Reviews</a>
-        </div>
+        </div> */}
```
Comment (tracyyh) [inline apps/web/src/app/_components/reviews/role-info.tsx:324]: I think we should just delete this if it's not reflected anymore in the figma

**Review by tracyyh — APPROVED** [review]
YAY
