### PR TITLE
limit number of roles created by a user

### LINKED ISSUE #171: (Develop) Limit # of Roles Created by A User
Let's make it so users can only create 4 roles. Once they hit this limit, the frontend component should be disabled **and** also the endpoint to create a review should fail. 

For the second point, you will probably need to update the "CreateRoleSchema" to include a "createdBy" so you know who is trying to hit that endpoint. Take a look at `create` in the `review.ts` api file to see how we send errors for people that leave too many reviews.

How you want to edit the db schema / store this info for this is up to you! if the migration succeeds I'm gonna hit approve! ◡̈

### PR DESCRIPTION
**Pull request by tracyyh**
## Description

Add 'createdBy' column to roles and an endpoint that returns the roles created by a profile

## Motivation and Context

Closes #171 

## Screenshots (if appropriate):

Screenshot 2025-04-01 at 8 56 25 PM

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Database migration
  - [x] Ran `pnpm db:generate` and verified generated SQL migration files in `packages/db/drizzle`

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have moved the ticket to "In Review"
- [ ] I have added reviewers to this PR
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

File: apps/web/src/app/_components/reviews/new-role-dialogue.tsx [hunk 1]
```diff
@@ -115,70 +126,75 @@ export default function NewRoleDialog({
...
-              </Button>
-            </DialogFooter>
-          </>
-        )}
-      </DialogContent>
+      {createdRolesCount && createdRolesCount >= 4 ? (
+        <DialogContent className="w-full bg-white py-14">
+          <DialogTitle>Sorry, you can only create up to 4 roles!</DialogTitle>
+        </DialogContent>
+      ) : (
```
Comment (tracyyh) [inline apps/web/src/app/_components/reviews/new-role-dialogue.tsx:133]: Code below did not change, just added this conditional that checks the created role count and displays an error if so

File: apps/web/src/app/_components/reviews/new-role-dialogue.tsx [hunk 2]
```diff
@@ -58,12 +59,22 @@ export default function NewRoleDialog({
   const [isSuccess, setIsSuccess] = useState(false);
   const company = api.company.getById.useQuery({ id: companyId });
   const [roleName, setRoleName] = useState("");
+
+  const { data: profile } = api.profile.getCurrentUser.useQuery();
+  const profileId = profile?.id;
+
+  const createdRoles =
+    profileId &&
+    api.role.getByCreatedBy.useQuery({ createdBy: profileId }).data;
```
Comment (banushi-a) [inline apps/web/src/app/_components/reviews/new-role-dialogue.tsx:68]: When we use react query / tanstack, we can't conditionally call the API like you do here ( I literally found this out 2 days ago lol)

Instead we have to use the `enabled` option inside of `useQuery`.
There is an example of this in `role-info.tsx` line 39

File: apps/web/src/app/_components/reviews/new-role-dialogue.tsx [hunk 3]
```diff
@@ -58,12 +59,22 @@ export default function NewRoleDialog({
...
+  const createdRolesCount = createdRoles?.length;
```
Comment (banushi-a) [inline apps/web/src/app/_components/reviews/new-role-dialogue.tsx:69]: I got the following error from when I navigated to the companies page. Also since Rishi and I just set up the staging environment database, there were no roles associated with my profile. So if the change I recommend above doesn't fix this you might need to edit this logic

Screenshot 2025-04-02 at 6 13 23 PM

**Review by banushi-a — CHANGES_REQUESTED** [review]
leggo

File: apps/web/src/app/_components/reviews/new-role-dialogue.tsx (hunk 3 above)
Comment (tracyyh) [reply apps/web/src/app/_components/reviews/new-role-dialogue.tsx]: hopefully fixed this, lmk if you run into it again bc i wasn't able to replicate the error even after removing all of my roles

**Review by banushi-a — APPROVED** [review]
yay it works, lgtm
